### ISSUE TITLE
error, although the mod itself is in the mods folder

### ISSUE THREAD

**Issue by Potochnyy** [tterrag1098/Registrate#40]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install registrate, any version.
Unmet dependency listing:
	 - Mod 'Create: Refabricated' (create) 0.4 requires any version of registrate, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install registrate, any version.
Unmet dependency listing:
	 - Mod 'Create: Refabricated' (create) 0.4 requires any version of registrate, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by tterrag1098** [comment]
The fabric version is unofficial, find it here: https://github.com/Create-Fabric/Registrate-Refabricated
